name: lines-of-code

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  lines-of-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@master

    uses: ./.github/actions/line-counter

    with:
      github_token: "${{ secrets.GITHUB_TOKEN }}"
