name: lines-of-code
on:
  push:
    branches: [master, main, 'releases/**']
jobs:
  loc:
    permissions: 'read-all | write-all'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/line-counter