name: lines-of-code
on:
  push:
    branches:
      - master
      - main
      - 'releases/**'

jobs:
  loc:
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v1
      with:
        ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
    
    - name: LOC
      uses: ./.github/actions/line-counter