name: lines-of-code
on:
  push:
    branches:
      - master
      - main
      - 'releases/**'

jobs:
  loc:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v1
      
    - name: LOC
      uses: ./.github/actions/line-counter
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        standard_token: ${{ secrets.ACTION_TOKEN }}